### ISSUE TITLE
Use the Project call nodes to target a device

### ISSUE THREAD

**Issue by Elevate-IT** [FlowFuse/nr-project-nodes#91]
### Description

Currently it is not possible to target a device using a Project call node.
This would be very helpful to request data from a device.

### Requested By

- Elevate-it

**Comment by ZJvandeWeg** [comment]
cc @joepavitt for scheduling considerations

**Comment by Steve-Mcl** [comment]
This is essentially a duplicate of https://github.com/FlowFuse/nr-project-nodes/issues/30 

It was identified in Jun 2023 that the project nodes should be made application aware and later the issue was updated to explicitly call out this part (targeting application bound devices)

I think we should close this new issue in favour of the original which calls out application awareness explicitly and mentions the deprecated endpoint the nodes currently use.
